In [28]:
import numpy as np 
import pandas as pd
import os
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [29]:
import tensorflow as tf
import matplotlib.pyplot as ply
import seaborn as sns
import pandas as pd
import numpy as np
from tensorflow.keras import layers, regularizers

import os
import zipfile

In [30]:
import matplotlib.pyplot as plt

In [31]:
local_zip ="/content/drive/MyDrive/People.zip"

In [32]:
zip_ref = zipfile.ZipFile(local_zip, 'r')
print(type(zip_ref))
zip_ref.extractall('/tmp/People/')
zip_ref.close()

<class 'zipfile.ZipFile'>


In [33]:
train_dir="/tmp/People/train"

In [34]:
df=pd.read_csv(os.path.join(train_dir, "train.csv"))
df
df1=pd.read_csv(os.path.join(train_dir, "train.csv"))

In [35]:
test=pd.read_csv("/tmp/People/test.csv")
test

Name
0     10005.jpg
1     10009.jpg
2     10015.jpg
3     10022.jpg
4     10023.jpg
...         ...
2458  18197.jpg
2459  18198.jpg
2460  18199.jpg
2461  18202.jpg
2462  18206.jpg

[2463 rows x 1 columns]

In [36]:
from sklearn.model_selection import train_test_split


In [37]:
train=df.loc[:4013,]
test=df.loc[4013:,]

In [38]:
train

Name  HeadCount
0     10001.jpg          4
1     10002.jpg          4
2     10003.jpg          2
3     10004.jpg          3
4     10006.jpg          4
...         ...        ...
4009  15732.jpg          4
4010  15734.jpg          2
4011  15735.jpg          3
4012  15736.jpg          3
4013  15737.jpg          3

[4014 rows x 2 columns]

In [39]:
test=test.reset_index(drop=True)
test

Name  HeadCount
0     15737.jpg          3
1     15739.jpg          3
2     15740.jpg          4
3     15746.jpg          2
4     15747.jpg          5
...         ...        ...
1715  18201.jpg          2
1716  18203.jpg          3
1717  18204.jpg          5
1718  18205.jpg          8
1719  18207.jpg          4

[1720 rows x 2 columns]

In [40]:
import shutil
for i in range(0, 4014):
  c=train.loc[i]['Name']
  src_path=os.path.join("/tmp/People/train/image_data", c)
  dst_path = "/tmp/project_train/train/"
  dst_path=dst_path+c
  shutil.copy(src_path, dst_path)
for i in range(0, 1719):
  c=test.loc[i]['Name']
  src_path=os.path.join("/tmp/People/train/image_data", c)
  dst_path = "/tmp/project_test/test/"
  dst_path=dst_path+c
  shutil.copy(src_path, dst_path)

In [41]:
train_dir="/tmp/project_train/train/"
test_dir = "/tmp/project_test/test/"

In [42]:
train['Name']=train_dir+train['Name']
train

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Name  HeadCount
0     /tmp/project_train/train/10001.jpg          4
1     /tmp/project_train/train/10002.jpg          4
2     /tmp/project_train/train/10003.jpg          2
3     /tmp/project_train/train/10004.jpg          3
4     /tmp/project_train/train/10006.jpg          4
...                                  ...        ...
4009  /tmp/project_train/train/15732.jpg          4
4010  /tmp/project_train/train/15734.jpg          2
4011  /tmp/project_train/train/15735.jpg          3
4012  /tmp/project_train/train/15736.jpg          3
4013  /tmp/project_train/train/15737.jpg          3

[4014 rows x 2 columns]

In [43]:
test['Name']=test_dir+test['Name']
test

Name  HeadCount
0     /tmp/project_test/test/15737.jpg          3
1     /tmp/project_test/test/15739.jpg          3
2     /tmp/project_test/test/15740.jpg          4
3     /tmp/project_test/test/15746.jpg          2
4     /tmp/project_test/test/15747.jpg          5
...                                ...        ...
1715  /tmp/project_test/test/18201.jpg          2
1716  /tmp/project_test/test/18203.jpg          3
1717  /tmp/project_test/test/18204.jpg          5
1718  /tmp/project_test/test/18205.jpg          8
1719  /tmp/project_test/test/18207.jpg          4

[1720 rows x 2 columns]

In [44]:
train_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

test_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255
)

In [45]:
train_images = train_generator.flow_from_dataframe(
    dataframe=train,
    x_col='Name',
    y_col='HeadCount',
    target_size=(224, 224),
    color_mode='rgb',
    class_mode='raw',
    batch_size=32,
    shuffle=True,
    seed=42,
    subset='training'
)

Found 3212 validated image filenames.


In [46]:
val_images = train_generator.flow_from_dataframe(
    dataframe=train,
    x_col='Name',
    y_col='HeadCount',
    target_size=(224, 224),
    color_mode='rgb',
    class_mode='raw',
    batch_size=32,
    shuffle=True,
    seed=42,
    subset='validation'
)

Found 802 validated image filenames.


In [47]:
test_images = test_generator.flow_from_dataframe(
    dataframe=test,
    x_col='Name',
    y_col='HeadCount',
    target_size=(224, 224),
    color_mode='rgb',
    class_mode='raw',
    batch_size=32,
    shuffle=False
)

Found 1719 validated image filenames.


/usr/local/lib/python3.7/dist-packages/keras/preprocessing/image.py:991: UserWarning: Found 1 invalid image filename(s) in x_col="Name". These filename(s) will be ignored.
  n_invalid, x_col))


In [48]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
# All images will be rescaled by 1./255
train_datagen = ImageDataGenerator(rescale=1./255)
val_datagen = ImageDataGenerator(rescale=1./255)





train_generator = train_datagen.flow_from_dataframe(
          dataframe=train, 
          directory=train_dir, 
          x_col="Name",
          y_col="HeadCount", 
          has_ext=True, 
          class_mode="other", 
          target_size=(224, 224), 
          batch_size=20)


Found 4014 validated image filenames.


In [61]:
from keras.applications.vgg16 import VGG16
base_model = VGG16(input_shape=(224,224,3), weights='imagenet', include_top=False)
base_model.trainable = True 
base_model.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [64]:
import tensorflow as tf
model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1, activation='linear')
])
model.summary()
model.compile(loss='mean_squared_error', optimizer = tf.keras.optimizers.Adam(learning_rate = 0.0001), metrics=[tf.keras.metrics.RootMeanSquaredError()])

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg16 (Functional)          (None, 7, 7, 512)         14714688  
                                                                 
 flatten_4 (Flatten)         (None, 25088)             0         
                                                                 
 dense_4 (Dense)             (None, 1)                 25089     
                                                                 
Total params: 14,739,777
Trainable params: 14,739,777
Non-trainable params: 0
_________________________________________________________________


In [69]:
history = model.fit(
      train_generator,
      steps_per_epoch=100,  # 2000 images = batch_size * steps
      epochs=30,
      validation_data=val_images,
      validation_steps=60,  # 1000 images = batch_size * steps
      verbose=1)

Epoch 1/30
100/100 [==============================] - ETA: 0s - loss: 5.6643 - root_mean_squared_error: 2.3800

100/100 [==============================] - 39s 387ms/step - loss: 5.6643 - root_mean_squared_error: 2.3800 - val_loss: 3.1599 - val_root_mean_squared_error: 1.7776
Epoch 2/30
100/100 [==============================] - 33s 324ms/step - loss: 4.6183 - root_mean_squared_error: 2.1490
Epoch 3/30
100/100 [==============================] - 32s 316ms/step - loss: 7.8502 - root_mean_squared_error: 2.8018
Epoch 4/30
100/100 [==============================] - 32s 314ms/step - loss: 7.3416 - root_mean_squared_error: 2.7095
Epoch 5/30
100/100 [==============================] - 31s 309ms/step - loss: 9.9493 - root_mean_squared_error: 3.1542
Epoch 6/30
100/100 [==============================] - 31s 313ms/step - loss: 9.1015 - root_mean_squared_error: 3.0169
Epoch 7/30
100/100 [==============================] - 31s 312ms/step - loss: 4.9299 - root_mean_squared_error: 2.2203
Epoch 8/30
100/100 [==============================] - 31s 311ms/step - loss: 6.2865 - root_mean_squared_error: 2.5073
Epoch 9/30

In [52]:
from sklearn.metrics import r2_score

In [70]:
rmse = np.sqrt(model.evaluate(test_images, verbose=0))
print("     Test RMSE: " + str(rmse))

     Test RMSE: [2.07259798 1.43965203]


In [71]:
predicted_ages = np.squeeze(model.predict(test_images))
predicted_ages=np.rint(predicted_ages)
predicted_ages

54/54 [==============================] - 15s 275ms/step


array([5., 5., 5., ..., 6., 6., 5.], dtype=float32)

In [73]:
r2 = r2_score(true_ages, predicted_ages)
print("Test R^2 Score: "+str(r2))

Test R^2 Score: 0.03709317993751449


In [74]:
historydict=history.history

In [75]:
historydict.keys()

dict_keys(['loss', 'root_mean_squared_error', 'val_loss', 'val_root_mean_squared_error'])

**EfficientNetB0**

In [83]:
from keras.applications.efficientnet import EfficientNetB0
base_model4 = EfficientNetB0(input_shape=(224,224,3), weights='imagenet', include_top=False)
base_model4.trainable = True 
base_model4.summary()

Model: "efficientnetb0"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 rescaling_1 (Rescaling)        (None, 224, 224, 3)  0           ['input_5[0][0]']                
                                                                                                  
 normalization_1 (Normalization  (None, 224, 224, 3)  7          ['rescaling_1[0][0]']            
 )                                                                                                
                                                                                     

In [84]:
model4 = tf.keras.Sequential([
    base_model4,
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(1, activation='linear')
])
model4.summary()
model4.compile(loss='mean_squared_error', optimizer = tf.keras.optimizers.Adam(learning_rate = 0.0001), metrics=[tf.keras.metrics.RootMeanSquaredError()])

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 efficientnetb0 (Functional)  (None, 7, 7, 1280)       4049571   
                                                                 
 flatten_5 (Flatten)         (None, 62720)             0         
                                                                 
 dense_5 (Dense)             (None, 1)                 62721     
                                                                 
Total params: 4,112,292
Trainable params: 4,070,269
Non-trainable params: 42,023
_________________________________________________________________


In [87]:
history2 = model4.fit(
      train_generator,
      steps_per_epoch=3212//60,  
      epochs=50,
      validation_data=val_images,
      validation_steps=60,  
      verbose=1)

Epoch 1/50
53/53 [==============================] - 11s 205ms/step - loss: 1.7269 - root_mean_squared_error: 1.3141
Epoch 2/50
53/53 [==============================] - 12s 227ms/step - loss: 1.4195 - root_mean_squared_error: 1.1914
Epoch 3/50
53/53 [==============================] - 11s 203ms/step - loss: 1.8162 - root_mean_squared_error: 1.3476
Epoch 4/50
53/53 [==============================] - 11s 202ms/step - loss: 2.8354 - root_mean_squared_error: 1.6839
Epoch 5/50
53/53 [==============================] - 11s 201ms/step - loss: 1.1936 - root_mean_squared_error: 1.0925
Epoch 6/50
53/53 [==============================] - 11s 202ms/step - loss: 1.3083 - root_mean_squared_error: 1.1438
Epoch 7/50
53/53 [==============================] - 12s 225ms/step - loss: 1.2946 - root_mean_squared_error: 1.1378
Epoch 8/50
53/53 [==============================] - 11s 202ms/step - loss: 1.2724 - root_mean_squared_error: 1.1280
Epoch 9/50
53/53 [==============================] - 11s 204ms/step - los

In [88]:
predicted_ages4 = np.squeeze(model4.predict(test_images))


54/54 [==============================] - 14s 229ms/step


In [89]:
true_ages = test_images.labels

In [90]:
predicted_ages4

array([1.872621 , 4.3389673, 1.2521446, ..., 4.099634 , 5.8954434,
       5.5316143], dtype=float32)

In [91]:
predicted_ages4=np.rint(predicted_ages4)
predicted_ages4

array([2., 4., 1., ..., 4., 6., 6.], dtype=float32)

In [92]:
rmse = np.sqrt(model4.evaluate(test_images, verbose=0))
print("     Test RMSE: " + str(rmse))

r2 = r2_score(true_ages, predicted_ages4)
print("Test R^2 Score: "+str(r2))

     Test RMSE: [1.81305009 1.34649546]
Test R^2 Score: 0.25812377343017623
